# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0004_twitterconfiguration_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitterconfiguration',
            name='languages',
            field=models.TextField(default='en'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='twitterconfiguration',
            name='topics',
            field=models.TextField(default='love'),
            preserve_default=False,
        ),
    ]
