# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0005_auto_20160427_0619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=200)),
                ('country_code', models.CharField(max_length=2)),
                ('country_language_code', models.CharField(max_length=200)),
                ('topics', models.TextField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='twitterconfiguration',
            name='geolocation',
            field=models.BooleanField(default=True),
        ),
    ]
