# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0006_auto_20160428_0451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='country_language_code',
        ),
        migrations.AddField(
            model_name='country',
            name='languages',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
